[package]
name = "go_box_import_template"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
glam = "0.33.1"
gltf = "1.4.1"
image = "0.25.10"
image-extras = "0.1" #{ version = "0.1", features = ["pcx"], default-features = false }
json = "0.12.4"
wit-bindgen = "0.57.1"
zip = "8.6.0"
